---
- name: Enable default NGINX site 
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: create symlink for default site from NGINX sites-enabled
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: restart NGINX service
      systemd:
        name: nginx
        state: restarted

